apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperdeck-mini-prometheus-exporter
  labels:
    app: hyperdeck-mini-prometheus-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperdeck-mini-prometheus-exporter
  template:
    metadata:
      labels:
        app: hyperdeck-mini-prometheus-exporter
    spec:
      containers:
        - name: hyperdeck-mini-prometheus-exporter
          image: branttaylor/hyperdeck-mini-prometheus-exporter:1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          env:
            - name: HYPERDECK_IP
              value: '10.0.0.100'
            # - name: PORT
            #   value: '8000'
            # - name: HOST
            #   value: '0.0.0.0'
            # - name: METRICS_PATH
            #   value: '/metrics'
            # - name: HEALTH_PATH
            #   value: '/healthz'
            # Above commented variables are unneeded if you are using the defaults
